apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: dispatch
replicas:
- name: dispatch
  count: 0
patches:
- target:
    kind: ConfigMap
    name: dispatch-settings
  patch: "- op: replace\n  path: /data/environment\n  value: broken\n"
