apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dispatch
  namespace: dispatch
  labels:
    app: dispatch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
      - name: api
        image: ${DOCKYARD_IMAGE}
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 128Mi
