// Auto-generated by scripts/generate_types.py. Do not edit manually.

export type Assessment = {
  "id": string;
  "unit_id": string;
  "revision": number;
  "lab_id": string;
  "status": CheckStatus;
  "started_at": string;
  "finished_at": string;
  "file_digest": string;
  "evidence": Array<Evidence>;
  "independent": boolean;
  "hints_used"?: number;
  "reference_revealed"?: boolean;
};

export type CheckStatus = "pass" | "fail" | "blocked" | "stale";

export type Command = {
  "args": Array<string>;
  "timeout"?: number;
  "stdin"?: string | null;
  "allowed_exit_codes"?: Array<number>;
};

export type Criterion = {
  "id": string;
  "title": string;
  "explanation": string;
  "command": Command;
  "expectation"?: "contains" | "equals" | "matches" | "json" | "absent";
  "expected": string;
  "output"?: "stdout" | "stderr" | "combined";
  "json_path"?: Array<string | number>;
  "diagnostic": string;
  "points"?: number;
};

export type Evidence = {
  "criterion": string;
  "title": string;
  "status": CheckStatus;
  "expected": string;
  "observed": string;
  "diagnostic": string;
  "points"?: number;
};

export type Lab = {
  "id": string;
  "unit_id": string;
  "revision": number;
  "runtime": Runtime;
  "state": "absent" | "preparing" | "ready" | "checking" | "stopping" | "stopped" | "failed" | "cleaning";
  "workspace": string;
  "created_at": string;
  "updated_at": string;
  "resources"?: Record<string, string>;
  "error"?: string | null;
};

export type Prediction = {
  "question": string;
  "options": Array<string>;
  "correct": number;
  "explanation": string;
};

export type Runtime = "docker" | "kubernetes" | "linux";

export type Unit = {
  "id": string;
  "revision"?: number;
  "module": number;
  "order": number;
  "title": string;
  "summary": string;
  "kind"?: UnitKind;
  "runtime": Runtime;
  "minutes": number;
  "outcomes": Array<string>;
  "prerequisites"?: Array<string>;
  "objectives"?: Array<string>;
  "concept": string;
  "brief": string;
  "debrief": string;
  "prediction": Prediction;
  "hints": Array<string>;
  "sources": Array<string>;
  "starter": Record<string, string>;
  "reference": Record<string, string>;
  "prepare"?: Array<Command>;
  "checks": Array<Criterion>;
  "capabilities"?: Array<string>;
  "checkpoint"?: string | null;
  "images"?: Array<string>;
  "alternatives"?: Array<string>;
  "failure_modes"?: Array<string>;
};

export type UnitKind = "lesson" | "mission" | "incident";
