"""Generate browser model types from the canonical Pydantic JSON schemas."""

import json
from pathlib import Path

from dockyard.models import Assessment, Lab, Unit


def render(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return " | ".join(render(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{render(schema['items'])}>"
    if kind == "object":
        if "properties" not in schema:
            return f"Record<string, {render(schema.get('additionalProperties', {}))}>"
        required = schema.get("required", [])
        fields = [
            f"  {json.dumps(name)}{'' if name in required else '?'}: {render(value)};"
            for name, value in schema["properties"].items()
        ]
        return "{\n" + "\n".join(fields) + "\n}"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


definitions = {}
for model in (Unit, Assessment, Lab):
    schema = model.model_json_schema()
    definitions.update(schema.pop("$defs", {}))
    definitions[model.__name__] = schema
output = "// Auto-generated by scripts/generate_types.py. Do not edit manually.\n\n"
output += "\n\n".join(
    f"export type {name} = {render(schema)};" for name, schema in sorted(definitions.items())
)
destination = Path(__file__).resolve().parents[1] / "frontend/src/contracts.gen.ts"
destination.parent.mkdir(parents=True, exist_ok=True)
destination.write_text(output + "\n")
