import { test, expect } from '@playwright/test';
import { spawn, execFileSync, type ChildProcess } from 'node:child_process';
import { mkdirSync, mkdtempSync } from 'node:fs';
import path from 'node:path';
import { once } from 'node:events';

const root = path.resolve(import.meta.dirname, '../..');
const binary = path.join(root, '.runtime/installed/bin/dockyard');
let server: ChildProcess;
let url: string;
let profile: string;

test.beforeAll(async () => {
  mkdirSync(path.join(root, '.runtime/e2e'), { recursive: true });
  profile = mkdtempSync(path.join(root, '.runtime/e2e/profile-'));
  execFileSync(path.join(root, '.runtime/installed/bin/python'), [path.join(root, 'frontend/e2e/seed_profile.py'), profile]);
  server = spawn(binary, ['--data-dir', profile, 'launch', '--port', '0', '--no-open'], { cwd: root });
  url = await new Promise<string>((resolve, reject) => {
    let output = '';
    const timeout = setTimeout(() => reject(new Error('Launcher did not announce its sign-in URL')), 15_000);
    server.stdout!.on('data', data => {
      output += data.toString();
      const match = output.match(/http:\/\/127\.0\.0\.1:\d+\/#session=[A-Za-z0-9_-]+/);
      if (match) { clearTimeout(timeout); resolve(match[0]); }
    });
    server.on('error', reject);
    server.on('exit', code => { clearTimeout(timeout); reject(new Error(`Launcher exited: ${code}`)); });
  });
});

test.afterAll(async () => {
  if (process.env.DOCKYARD_INTEGRATION === '1') {
    execFileSync(binary, ['--data-dir', profile, 'lab', 'clean', 'm01-processes', '--yes']);
    execFileSync(binary, ['--data-dir', profile, 'lab', 'clean', 'm01-mission', '--yes']);
  }
  if (server && server.exitCode === null) { server.kill('SIGINT'); await once(server, 'exit'); }
});

test('installed workbench teaches, remembers observations, and handles real lab lifecycle', async ({ page }) => {
  const failures: string[] = [];
  page.on('pageerror', error => failures.push(error.message));
  await page.goto(url);
  await expect(page.getByRole('heading', { name: 'Build understanding. Then build the system.' })).toBeVisible();
  expect(page.url()).not.toContain('session=');
  await page.getByRole('button', { name: 'Start learning' }).click();
  await expect(page.getByRole('heading', { name: 'A container is a running process', exact: true })).toBeVisible();
  const understand = page.getByRole('tab', { name: 'Understand' });
  await understand.focus();
  await page.keyboard.press('ArrowRight');
  await expect(page.getByRole('tab', { name: 'Your task' })).toBeFocused();
  await page.getByRole('button', { name: 'Reveal hint 1' }).click();
  await expect(page.getByText('HINT 1', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Reveal reference', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button', { name: 'Keep working' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  const notes = page.getByRole('textbox', { name: 'Notes for this lesson' });
  await notes.fill('The process and its published port are separate observations.');
  await page.getByRole('button', { name: 'Save observations' }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Continue lesson' }).click();
  await expect(notes).toHaveValue('The process and its published port are separate observations.');
  for (const width of [760, 480]) {
    await page.setViewportSize({ width, height: 1000 });
    await expect(notes).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Use light theme' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  if (process.env.DOCKYARD_INTEGRATION === '1') {
    await page.getByRole('button', { name: 'Prepare lab' }).click();
    await expect(page.getByRole('button', { name: 'Open in WezTerm' })).toBeEnabled();
    await page.getByRole('button', { name: 'Check work', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Here is what the lab observed.' })).toBeVisible();
    execFileSync(path.join(root, '.runtime/installed/bin/python'), [path.join(root, 'frontend/e2e/repair_lab.py'), profile, 'm01-processes']);
    await page.getByRole('button', { name: 'Refresh resource observation' }).click();
    await expect(page.getByRole('region', { name: 'Observed lab resources' }).getByRole('button', { name: /^Container / })).toBeVisible();
    await page.getByRole('button', { name: 'Check work', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'The required behavior passed this check.' })).toBeVisible();
    await page.getByRole('button', { name: 'Stop', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'The required behavior passed this check.' })).toBeVisible();
    await page.getByRole('button', { name: 'Check work', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'The environment needs attention.' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Resume', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Stop', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Reset', exact: true }).click();
    await page.getByRole('button', { name: 'Continue', exact: true }).click();
    await expect(page.getByText('Reset completed.', { exact: true })).toBeVisible();
    await page.getByRole('textbox', { name: 'Search lessons' }).fill('m01-mission');
    await page.getByRole('button', { name: /Mission: restore the first Dispatch service/ }).click();
    await page.getByRole('button', { name: 'Prepare lab' }).click();
    await expect(page.getByRole('button', { name: 'Open in WezTerm' })).toBeEnabled();
    await page.getByRole('tab', { name: 'Your task' }).click();
    await page.getByRole('button', { name: 'Reveal hint 1' }).click();
    await expect(page.getByText('HINT 1', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Independent retake', exact: true }).click();
    await expect(page.getByRole('dialog')).toContainText('Previous evidence and notes remain');
    await page.getByRole('button', { name: 'Continue', exact: true }).click();
    await expect(page.getByText('Retake completed.', { exact: true })).toBeVisible();
    await expect(page.getByText('HINT 1', { exact: true })).not.toBeVisible();
    await expect(page.getByRole('button', { name: 'Reveal hint 1' })).toBeVisible();
  }
  await page.getByRole('textbox', { name: 'Search lessons' }).fill('reconciliation');
  await page.getByRole('button', { name: /Let a controller maintain the application/ }).click();
  const model = page.getByRole('region', { name: 'Explore reconciliation' });
  await model.getByRole('button', { name: 'Delete model Pod 1', exact: true }).click();
  await expect(model.getByRole('status')).toContainText('1 observed / 2 desired');
  await model.getByRole('button', { name: 'Advance controller' }).click();
  await expect(model.getByRole('status')).toContainText('Created Pod 3');
  await expect(model.getByRole('status')).toContainText('2 observed / 2 desired');
  await page.setViewportSize({ width: 480, height: 1000 });
  await model.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('textbox', { name: 'Search lessons' }).fill('m11-claims');
  await page.getByRole('button', { name: /Connect claims to durable database storage/ }).click();
  const storage = page.getByRole('region', { name: 'Explore storage lifetimes' });
  await expect(page.getByRole('heading', { level: 1 })).toHaveCount(1);
  await storage.getByRole('button', { name: 'Remove workload' }).click();
  await storage.getByRole('button', { name: 'Start replacement Pod' }).click();
  await expect(storage.getByText('Pod 2', { exact: true })).toBeVisible();
  await expect(storage.getByText('2 stored records', { exact: true })).toBeVisible();
  await storage.getByRole('button', { name: 'Remove workload' }).click();
  await storage.getByRole('combobox', { name: 'PV reclaim policy' }).selectOption('Retain');
  await storage.getByRole('button', { name: 'Delete claim' }).click();
  await expect(storage.getByText('Released volume', { exact: true })).toBeVisible();
  await expect(storage.getByRole('button', { name: 'Start replacement Pod' })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 480, height: 1000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('textbox', { name: 'Search lessons' }).fill('m08-mission');
  await page.getByRole('button', { name: /Mission: process work and prove maintenance/ }).click();
  await expect(page.locator('.metadata')).toContainText('Review needed');
  await page.getByRole('textbox', { name: 'Search lessons' }).fill('m13-mission');
  await page.getByRole('button', { name: /Keep Dispatch available through worker maintenance/ }).click();
  await page.getByRole('tab', { name: 'Evidence' }).click();
  await page.getByText('Measured state', { exact: true }).click();
  await expect(page.locator('details[open]')).toContainText('dispatch-fixture-a');
  await page.setViewportSize({ width: 480, height: 1000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Reference desk', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'A reference you can work with.' })).toBeVisible();
  await page.getByRole('button', { name: 'Glossary 66 terms' }).click();
  await page.getByRole('textbox', { name: 'Search glossary' }).fill('quorum');
  await expect(page.locator('.glossary-term')).toHaveCount(1);
  await expect(page.getByRole('heading', { name: 'Quorum', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Keep the API writable through a control-plane outage', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Keep the API writable through a control-plane outage');
  const quorum = page.getByRole('region', { name: 'Explore API routing and etcd quorum' });
  await quorum.getByRole('button', { name: 'Try a fresh write' }).click();
  await expect(quorum.getByRole('status')).toContainText('Write failed at the endpoint');
  await quorum.getByRole('checkbox', { name: 'Route to control plane 2' }).check();
  await quorum.getByRole('button', { name: 'Try a fresh write' }).click();
  await expect(quorum.getByRole('status')).toContainText('fresh write committed');
  await quorum.getByRole('button', { name: 'Stop control plane 2' }).click();
  await quorum.getByRole('checkbox', { name: 'Route to control plane 3' }).check();
  await quorum.getByRole('button', { name: 'Try a fresh write' }).click();
  await expect(quorum.getByRole('status')).toContainText('write cannot commit');
  await page.setViewportSize({ width: 480, height: 1000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Quorum', exact: true }).click();
  await expect(page.getByRole('textbox', { name: 'Search glossary' })).toHaveValue('Quorum');
  await page.getByRole('button', { name: 'Return to your lesson' }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Keep the API writable through a control-plane outage');
  await page.getByRole('button', { name: 'Open reference desk' }).click();
  await page.setViewportSize({ width: 480, height: 1000 });
  await page.getByRole('combobox', { name: 'Foundation primer' }).selectOption('yaml');
  await expect(page.getByRole('heading', { name: 'Read YAML as a data structure' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Incident scenarios', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Follow the evidence.' })).toBeVisible();
  await page.getByRole('combobox', { name: 'Environment', exact: true }).selectOption('docker');
  await expect(page.locator('.unitrow')).toHaveCount(4);
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0);
  expect(await page.locator('.skip').evaluate(element => element.getBoundingClientRect().bottom <= 0)).toBe(true);
  await page.screenshot({ path: path.join(root, '.artifacts/incidents-wide.png'), fullPage: true });
  await page.setViewportSize({ width: 480, height: 1000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: path.join(root, '.artifacts/incidents-narrow.png'), fullPage: true });
  await page.getByRole('textbox', { name: 'Search incidents' }).fill('worker-only');
  await expect(page.locator('.unitrow')).toHaveCount(1);
  await page.locator('.unitrow').click();
  await expect(page.locator('.lesson-heading')).toContainText('INCIDENT SCENARIO');
  await page.locator('.lesson-heading').getByRole('button', { name: 'Incident scenarios', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Follow the evidence.' })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Spaced review', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Make the skill available again.' })).toBeVisible();
  const dueReviews = page.getByRole('region', { name: 'Activities due for review' });
  await expect(dueReviews.getByRole('button', { name: /Keep Dispatch available through worker maintenance/ })).toBeVisible();
  await expect(dueReviews.getByText('The lesson revision changed; earlier evidence remains in your record.')).toBeVisible();
  await page.screenshot({ path: path.join(root, '.artifacts/review-wide.png'), fullPage: true });
  await page.setViewportSize({ width: 480, height: 1000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: path.join(root, '.artifacts/review-narrow.png'), fullPage: true });
  for (const label of await page.locator('.unitmeta > span').all()) {
    expect(await label.evaluate(element => element.getBoundingClientRect().height <= parseFloat(getComputedStyle(element).lineHeight) + 1)).toBe(true);
  }
  await expect(dueReviews.getByRole('button', { name: /Keep Dispatch available through worker maintenance/ }).locator('.unitmeta')).toHaveText('65 min');
  await dueReviews.getByRole('button', { name: /Keep Dispatch available through worker maintenance/ }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Keep Dispatch available through worker maintenance');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Practical placement', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Find the gaps worth your time.' })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Placement benchmarks' }).locator('article')).toHaveCount(4);
  await expect(page.locator('.placement-recommendation')).toContainText('Container engineering');
  await expect(page.locator('.topbar')).toContainText('Practical placement');
  await page.screenshot({ path: path.join(root, '.artifacts/placement-wide.png'), fullPage: true });
  await page.setViewportSize({ width: 480, height: 1000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: path.join(root, '.artifacts/placement-narrow.png'), fullPage: true });
  await page.getByRole('button', { name: 'Try the benchmark' }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Capstone: deliver and recover Dispatch');
  expect(failures).toEqual([]);
  // Keep the browser and its SSE connection open while verifying foreground shutdown.
  const stopped = once(server, 'exit');
  server.kill('SIGINT');
  const result = await Promise.race([stopped, new Promise((_, reject) => setTimeout(() => reject(new Error('Launcher did not stop with an open event stream')), 8_000))]);
  expect(result).toEqual([0, null]);
});
